### ISSUE TITLE
Dictionary Support

### ISSUE THREAD

**Issue by Awendel** [antoniomuso/lz4-napi#242]
Compression ratios of small files / objects can be improved by a magnitude by using a compression dictionary,
for example generated via zstd on training data.

Since the original LZ4 supports Dictionaries, it would be great to have it as a feature here too, as part of the API.

**Comment by antoniomuso** [comment]
I am sorry, I miss the notification. 

I agree, It seems a good feature.

**Comment by antoniomuso** [comment]
Hello Awendel, dictionaries are now supported with the new version [2.2.0](https://github.com/antoniomuso/lz4-napi/releases/tag/v2.2.0)!

**Comment by Awendel** [comment]
great work!

I'll take it for a spin and will report back should there be any issues!
