### ISSUE TITLE
Error: the offset to copy is not contained in the decompressed buffer

### ISSUE THREAD

**Issue by alex-vukov** [antoniomuso/lz4-napi#544]
No matter what buffer I try to decompress I always get this error: `Error: the offset to copy is not contained in the decompressed buffer`. The same buffer gets successfully decompressed by the `lz4` library using `decode`. The same error happens both on `uncompress` and `uncompressSync`.

**Comment by antoniomuso** [comment]
Probably there is different offset formatting, how do you compress the buffer, what is the library do you use?

**Comment by alex-vukov** [comment]
I compress the buffer using lz4 compress(). The buffer is in LZ4 frame format. Does lz4-napi only support the block format?

**Comment by antoniomuso** [comment]
Sorry for response delay, yes currently support only block format.

**Comment by kravets-levko** [comment]
Hi @antoniomuso! Are there any plans to support LZ4 frame format? We currently use [LZ4](https://github.com/pierrec/node-lz4) library, which supports it. But recently it was archived, and is not going to be supported anymore. So I'm looking for replacement for it. Unfortunately, I haven't found other LZ4 library for node with LZ4 frame format support. Your library looks the most promising so far - I see that [lz4_flex](https://github.com/PSeitz/lz4_flex) supports frame format, but don't know how easy it is to add it to this library

**Comment by antoniomuso** [comment]
Hi @kravets-levko, sorry for the late response. I don't know how hard it is. I don't have time to do it now, but if someone wants to start working on it, I can help him.

**Comment by antoniomuso** [comment]
Hi @kravets-levko, this feature is up with the last release [2.8.0](https://github.com/antoniomuso/lz4-napi/releases/tag/v2.8.0)

**Comment by kravets-levko** [comment]
Thank you so much @antoniomuso! I will try it next week and will provide you a feedback. I really appreciate all your effort for maintaining this project!
