### ISSUE TITLE
AWS Lambda runtime support

### ISSUE THREAD

**Issue by skhaz** [antoniomuso/lz4-napi#569]
Hi, first of all, thank you for the library, it was difficult to find one for Lz4 for NodeJS. Second, could you provide binaries for the AWS Lambda runtime?

I tried using `@antoniomuso/lz4-napi-linux-arm64-gnu` but was unsuccessful and encountered the following error:

```
Error: Runtime exited with error: signal: killed
Runtime.ExitError
```

Thank you.

**Comment by antoniomuso** [comment]
Hi @skhaz, I don't know it doesn't work. I don't have the machine to test it. I suggest you build this repository in the architecture that you are using. This library allows you to use your custom binary file: https://github.com/antoniomuso/lz4-napi/blob/main/index.js#L195

**Comment by skhaz** [comment]
I've decided to use ZSTD instead.
